project:
  type: website

website:
  title: "Rhi's recipes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/statsRhian
      - icon: twitter
        href: https://twitter.com/StatsRhian
format:
  html:
    theme: minty
    css: styles.css



