project:
  type: website

website:
  title: "Recipes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/statsRhian
      - icon: twitter
        href: https://twitter.com/StatsRhian
format:
  html:
    theme: cosmo
    css: styles.css



