---
title: "Aubergine and chickpea curry"
author: "[Michelle Alston](https://www.thelastfoodblog.com/aubergine-spinach-chickpea-curry/)"
categories: [curry, vegan]
description: "A rich curry with roasted aubergine"
---

- 1 aubergine, cubed
- 1 onion
- 1 thumb of ginger
- 3 cloves of garlic
- 1 red chilli pepper
- 1 tin of tomatoes
- 2 tsp cumin seeds
- 1 tsp yellow mustard seeds
- 1 tst turmeric
- 1 tsp ground coriander
- 1 tsp garam masala
- 1 tin of chickpeas
- 1 tin of coconut milk
- 50g baby spinach
- fresh coriander

1. Cook onion gently cook over low heat for about 20 minutes. The onions should be soft and light brown.
1. Heat the oven to 180° C fan
1. Roast aubergine drizzled in oil on a baking tray for 15 minutes
1. Toast the mustard seeds and cumin seeds in a dry pan until they release their aromas, about a minute.
1. Transfer them to a pestle and mortar and pound them until they are a rough powder.
1. Once the onion is soft and golden add the garlic, ginger and chilli pepper.
1. Cook for about 1 minute, then add all spices.
1. Cook for another minute, until you can smell the spices. Be careful not to let the spices burn.
1. Add tomatoes. Stir and leave to simmer over low heat for 10 minutes. 
1. Add the roasted aubergine and chickpeas
1. Pour in the coconut milk. Simmer for 5 minutes.
1. Add in the spinach and cook until the spinach has wilted.
