---
title: "Puy lentil lasagne"
author: "[The Hairy Bikers](https://www.bbc.co.uk/food/recipes/puy_lentil_lasagne_23244)"
categories: [pasta]
description: "I don't often bother to make lasagne, but when I do, I make this one"
---

* 200g puy lentils (or 1 tin of green lentils)
* 1 stock cube
* 1 onion, chopped
* 2 garlic cloves, chopped
* celery
* 1 carrot, chopped
* 110g mushrooms, finely diced
* 110g leek, finely sliced
* 1 tin chopped tomatoes
* 6-9 sheets lasagne
* handful grated Parmesan
* 110g butter
* 85g plain flour (sifted)
* 850ml milk

1. Preheat the oven to 180C.
1. For the lentil ragù, cover the lentils with cold water and bring to the boil. Crumble in the vegetable stock cube and cook for 15-20 minutes, or until the lentils are tender, then drain. Add a little more water if the mixture looks dry.
1. Fry onion, garlic, carrot, mushrooms and leek etc. for about five minutes, or until softened.
1. Stir in the cooked lentils and simmer gently for five minutes, then stir in the tomatoes. Cover with a lid and simmer on a low heat for 10-15 minutes. Season, to taste, with sea salt and freshly ground black pepper.
1. Meanwhile, for the cheese sauce, melt the butter in a medium saucepan over a medium-high heat then mix in the flour and stir until bubbling. Gradually add the milk, whisking constantly, until the mixture is smooth.
1. Simmer gently, stirring constantly, until the sauce starts to thicken and remove from heat.
1. Assemble the lasagne (repeat: lentils, cheese, pasta, finishing on the cheese). Sprinkle over the parmesan cheese and bake in the oven for 30-40 minutes, or until bubbling and golden-brown.

