---
title: "Green eggs"
author: "[Hattie Ellis](https://www.bbc.co.uk/food/recipes/butter-poached_egg_in_a_26822)"
categories: [breakfast]
description: "Healthy breakfast"
---
Serves 2

* 10g butter
* 125g baby spinach
* 5 cherry tomatos
* 1 egg
* squeeze of lemon juice

1. Melt some of the butter in frying pan
1. Add spinach & tomatoes and put lid on and let wilt
1. Make a ring in the mixture, re-butter and crack egg. Cook for 3 mins for runny yolk


1. Drain the jar of roasted peppers and put them into a food processor or into a bowl.
1. Take the stalks off the chillies, and deseed them if you don’t like it really hot. Add to the processor or bowl.
1. Tip in the garlic clove, and lime zest and juice. Cut the stalks off the coriander and add these, too. Process or whiz with a stick blender until paste*like.
1. Add the coriander leaves and salt and process or blend again, then pour the oil down the funnel of the processor as the motor is running, or pour the oil into your bowl and whiz again with a stick blender. It will make a sauce that is more liquid than a salsa, but soft and spoonable rather than a pouring sauce.
