---
title: "Banana bread"
author: "[Felicity Cloake](https://www.theguardian.com/lifeandstyle/wordofmouth/2012/aug/30/how-to-cook-perfect-banana-bread)"
categories: [cakes]
description: "From the Guardian perfect series"
---

- 350g ripe bananas (peeled weight)
- 180g plain flour, plus extra for the tin
- 2½ tsp baking powder
- 1 tsp salt
- 160g soft, light brown sugar
- 2 eggs, beaten
- 4 tbsp melted butter, plus extra to grease, slightly cooled
- 50g walnuts, roughly chopped

1. Preheat the oven to 150°C fan. Put two-thirds of the peeled banana chunks into a bowl and mash until smooth. Roughly mash the remainder and stir in gently.

2. Sift the flour, baking powder and salt into a bowl, and grease and lightly flour a 2lb tin.

3. Put the sugar, eggs and melted butter in a large bowl and use an electric mixer to whisk them until pale and slightly increased in volume. Fold in the bananas and the dry ingredients until you can see no more flour, then fold in the walnuts.

4. Spoon into the tin and bake for about an hour until a skewer inserted into the middle comes out clean. Cool in the tin for 10 minutes before turning out on to a rack to cool completely.